### ISSUE TITLE
missing a manifest.json file. causes first load to stop, 

### ISSUE THREAD

**Issue by russellii** [NathanVaughn/msfs-mod-manager#18]
![image](https://user-images.githubusercontent.com/388908/93005290-eedf6380-f58e-11ea-9700-2f68d4346d98.png)
Error 
Unable to parse mod tiger moth CVT . This is 
likely due to it missing a manifest.json file. 

removing the offending directory on restart allows it to phrase the rest.

**Comment by russellii** [comment]
This is the directory that crashed the reading section
[ants tiger moth_CVT_.zip](https://github.com/NathanVaughn/msfs-mod-manager/files/5213334/ants.tiger.moth_CVT_.zip)

**Comment by NathanVaughn** [comment]
It can't parse the `manifest.json` file that all MSFS mods are required to have, since it doesn't appear to be there. See [this topic](https://www.fsdeveloper.com/forum/threads/guide-creating-livery-packages-for-msfs.448795/) for more info on that.

Having a single mod be unparseable shouldn't prevent the whole mod manager from loading, so I'm working on fixing that.

**Comment by NathanVaughn** [comment]
Should be fixed in [v0.3.6](https://github.com/NathanVaughn/msfs-mod-manager/releases/tag/v0.3.6)
