### ISSUE TITLE
include compression to disabled files 

### ISSUE THREAD

**Issue by feiercrack** [NathanVaughn/msfs-mod-manager#40]
dunno where to put this request in, so i put it in here.
if wrong, please put it in the right place. thanks!

could we please have the disabled mods as an compressed zip file to save diskspace? (7zip,rar)
to install from zip file we already have :-)
i´ve edited the config.ini with my desired "disabled" folder.
works great. thanks!

and please can u add the modsize to the tab?
![1cc0d91d57de45f8a4beef3a65983e63](https://user-images.githubusercontent.com/47046040/95941935-3d785b80-0de2-11eb-836a-60a3b7e892c3.png)

**Comment by NathanVaughn** [comment]
I'm going to add this to the backlog, since this would require a huge restructuring on how the program handles mods. It's looking for the `manifest.json` file in every mod, and obviously, it can't find them in a `.zip` file. That would require a side-database to remember what has disabled and zipped.

**Comment by NathanVaughn** [comment]
Going to close this issue as this would be extremely difficult to implement with symlinks (#48) and completely remove the performance benefit of symlinks.
