### ISSUE TITLE
unable to open 

### ISSUE THREAD

**Issue by PlayingGamez331** [NathanVaughn/msfs-mod-manager#62]
## Expected Behavior
being able to open the application
## Actual Behavior
fails to execute script main
## Steps to Reproduce the Problem
opening the application
# Specifications

  - Application Version: `v1.0.2`
  - MSFS Edition: MS store

## Debug Log Contents (only if reporting a bug)

[debug.log](https://github.com/NathanVaughn/msfs-mod-manager/files/6101718/debug.log)

**Comment by NathanVaughn** [comment]
Looks like something broke that I didn't see on my dev environment. I've pulled the release until I can investigate.

**Comment by NathanVaughn** [comment]
For now, manually downgrade to the previous version

**Comment by PlayingGamez331** [comment]
I did but thanks for reminding



________________________________

**Comment by calou952002** [comment]
Thank's for your answer.
I have reinstalled the previous version but the  problem is the same..

**Comment by PlayingGamez331** [comment]
which did you install cause i installed 1.0.0 and it works fine(that was the version i had before)

**Comment by calou952002** [comment]
It's ok with 1.00 version,  Thank you.  
-------- Message d'origine --------De : PlayingGamez331 <notifications@github.com> Date : 08/03/2021  17:26  (GMT+01:00) À : NathanVaughn/msfs-mod-manager <msfs-mod-manager@noreply.github.com> Cc : calou952002 <calou952002@yahoo.fr>, Comment <comment@noreply.github.com> Objet : Re: [NathanVaughn/msfs-mod-manager] unable to open  (#62) 
which did you install cause i installed 1.0.0 and it works fine(that was the version i had before)

**Comment by NathanVaughn** [comment]
Unfortunately I'm not able to replicate the issue on my setup with Steam or a friend's setup with MS Store. For context, the "Unable to execute script main" error means the underlying Python program never even started, as something was catastrophically wrong (like a syntax error), and thus my own logging never got a chance to write anything. 

I'm going to work on coming up with the best way to produce a debug executable without causing anyone else's mod manager to automatically download it. What would be immensely helpful is if someone installed the development environment as described in the README and reported on what happens when they try to run it.

**Comment by PlayingGamez331** [comment]
i'd like to help but i'm not sure on what to do, so should we maybe get in a call and do it together?
i'm in timezone UTC +1

**Comment by NathanVaughn** [comment]
Okay, some good news, I setup builds on GitHub separate from the releases (so that people's clients don't auto-update themselves) and I can replicate the issue now. Something with the build is broken. 

Will update after I've determined a fix.

**Comment by NathanVaughn** [comment]
Created new release [v1.0.3](https://github.com/NathanVaughn/msfs-mod-manager/releases/tag/v1.0.3). Let me know if this works.

**Comment by PlayingGamez331** [comment]
works great

**Comment by NathanVaughn** [comment]
No one else has said anything that differs so I'm going to close this.
